import React, { useState, useEffect, useRef } from 'react';
import './App.css';

function App() {
  const [messages, setMessages] = useState(() => {
    const saved = localStorage.getItem('director_chat_history');
    return saved ? JSON.parse(saved) : [{ sender: 'ai', text: 'Master Director OS ready. What shall we create today?' }];
  });
  
  const [currentResult, setCurrentResult] = useState(() => {
    const saved = localStorage.getItem('director_current_result');
    return saved || 'Waiting for script generation...';
  });

  const [input, setInput] = useState('');
  const messagesEndRef = useRef(null);

  useEffect(() => {
    localStorage.setItem('director_chat_history', JSON.stringify(messages));
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  useEffect(() => {
    localStorage.setItem('director_current_result', currentResult);
  }, [currentResult]);

  const handleSend = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      if (!input.trim()) return;

      const userMsg = { sender: 'user', text: input };
      setMessages(prev => [...prev, userMsg]);
      setInput('');

      // Mocking AI Response for now (until Google AI Studio API is hooked up)
      setTimeout(() => {
        const aiMsg = { sender: 'ai', text: 'Processing your vision... I have updated the script canvas on the right.' };
        setMessages(prev => [...prev, aiMsg]);
        setCurrentResult(`// [GENERATED BY MASTER DIRECTOR OS]\n// Based on: "${userMsg.text}"\n\n**🎥 SINGLE SCENE [0-15s]**\n\nCinematic live-action realism, Arri Alexa 65mm. STRICT SPATIAL CONTINUITY...\n\n(Note: Connect your Gemini API in App.jsx to replace this mock text.)`);
      }, 1000);
    }
  };

  const clearHistory = () => {
    setMessages([{ sender: 'ai', text: 'Memory cleared. Master Director OS ready.' }]);
    setCurrentResult('Waiting for script generation...');
  };

  return (
    <div className="app-container">
      {/* Left Chat Panel */}
      <div className="chat-panel">
        <div className="chat-header">
          <h1>Director OS</h1>
        </div>
        <div className="chat-messages">
          {messages.map((msg, i) => (
            <div key={i} className={`message ${msg.sender}`}>
              {msg.text}
            </div>
          ))}
          <div ref={messagesEndRef} />
        </div>
        <div className="chat-input-container">
          <textarea
            className="chat-input"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleSend}
            placeholder="Type your direction here (Press Enter to send)..."
          />
        </div>
      </div>

      {/* Right Result Panel */}
      <div className="result-panel">
        <div className="result-header">
          <h2>Production Canvas</h2>
          <button className="btn" onClick={clearHistory}>Reset Project</button>
        </div>
        <div className="result-content">
          {currentResult}
        </div>
      </div>
    </div>
  );
}

export default App;
